version: '3.8'

services:
  db:
    image: postgres:16
    container_name: test_app_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    restart: unless-stopped
    build:
      context: .
    user: "${UID}:${GID}"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: